export type GreenApiHttp = "GET" | "POST";

export interface GreenApiMethodDef {
  method: string;
  label: string;
  category: string;
  http: GreenApiHttp;
  description: string;
  bodyExample?: Record<string, unknown>;
  queryParams?: string[];
}

export const GREEN_API_CATEGORIES = [
  { id: "account", label: "Compte & instance" },
  { id: "sending", label: "Envoi de messages" },
  { id: "receiving", label: "Réception & files" },
  { id: "journals", label: "Historiques" },
  { id: "queues", label: "Files d'attente" },
  { id: "groups", label: "Groupes" },
  { id: "statuses", label: "Statuts WhatsApp" },
  { id: "marks", label: "Marquage lu" },
  { id: "service", label: "Chats & contacts" },
  { id: "media", label: "Fichiers & médias" },
] as const;

/** Catalogue des méthodes Green-API exposées dans la console UI. */
export const GREEN_API_METHODS: GreenApiMethodDef[] = [
  {
    method: "getStateInstance",
    label: "État de l'instance",
    category: "account",
    http: "GET",
    description: "authorized, notAuthorized, blocked, etc.",
  },
  {
    method: "getSettings",
    label: "Paramètres instance",
    category: "account",
    http: "GET",
    description: "Webhook, notifications, délais d'envoi…",
  },
  {
    method: "setSettings",
    label: "Modifier paramètres",
    category: "account",
    http: "POST",
    description: "Configurer webhook, notifications entrantes…",
    bodyExample: { webhookUrl: "", incomingWebhook: "yes", outgoingWebhook: "yes" },
  },
  {
    method: "getQR",
    label: "QR code connexion",
    category: "account",
    http: "GET",
    description: "Image base64 pour scanner WhatsApp",
  },
  {
    method: "reboot",
    label: "Redémarrer l'instance",
    category: "account",
    http: "GET",
    description: "Redémarre l'instance Green-API",
  },
  {
    method: "logout",
    label: "Déconnecter WhatsApp",
    category: "account",
    http: "GET",
    description: "Délie le téléphone de l'instance",
  },
  {
    method: "sendMessage",
    label: "Envoyer un texte",
    category: "sending",
    http: "POST",
    description: "Message texte à un chat ou groupe",
    bodyExample: { chatId: "229XXXXXXXX@c.us", message: "Bonjour !" },
  },
  {
    method: "sendFileByUrl",
    label: "Envoyer fichier (URL)",
    category: "sending",
    http: "POST",
    description: "Image, vidéo, audio, document via URL publique",
    bodyExample: {
      chatId: "229XXXXXXXX@c.us",
      urlFile: "https://example.com/image.jpg",
      fileName: "image.jpg",
    },
  },
  {
    method: "sendLocation",
    label: "Envoyer une position",
    category: "sending",
    http: "POST",
    description: "Coordonnées GPS",
    bodyExample: { chatId: "229XXXXXXXX@c.us", latitude: 6.37, longitude: 2.43, nameLocation: "Cotonou" },
  },
  {
    method: "sendContact",
    label: "Envoyer un contact",
    category: "sending",
    http: "POST",
    description: "Partager une fiche contact",
    bodyExample: { chatId: "229XXXXXXXX@c.us", contact: { phoneContact: 22900000000, firstName: "Jean" } },
  },
  {
    method: "sendPoll",
    label: "Envoyer un sondage",
    category: "sending",
    http: "POST",
    description: "Sondage WhatsApp",
    bodyExample: {
      chatId: "229XXXXXXXX@g.us",
      message: "Votre avis ?",
      options: [{ optionName: "Oui" }, { optionName: "Non" }],
      multipleAnswers: false,
    },
  },
  {
    method: "forwardMessages",
    label: "Transférer des messages",
    category: "sending",
    http: "POST",
    description: "Transférer vers un autre chat",
    bodyExample: { chatId: "229XXXXXXXX@c.us", chatIdFrom: "229YYYYYYYY@c.us", messages: ["idMessage1"] },
  },
  {
    method: "sendInteractiveButtons",
    label: "Boutons interactifs",
    category: "sending",
    http: "POST",
    description: "Message avec boutons",
    bodyExample: {
      chatId: "229XXXXXXXX@c.us",
      body: { text: "Choisissez" },
      action: { buttons: [{ type: "reply", buttonId: "1", buttonText: "OK" }] },
    },
  },
  {
    method: "receiveNotification",
    label: "Recevoir notification",
    category: "receiving",
    http: "GET",
    description: "Prochaine notification de la file HTTP",
    queryParams: ["receiveTimeout"],
  },
  {
    method: "lastIncomingMessages",
    label: "Derniers messages entrants",
    category: "receiving",
    http: "GET",
    description: "Messages entrants récents sur l'instance",
  },
  {
    method: "lastOutgoingMessages",
    label: "Derniers messages sortants",
    category: "receiving",
    http: "GET",
    description: "Messages sortants récents",
  },
  {
    method: "getChatHistory",
    label: "Historique d'un chat",
    category: "journals",
    http: "POST",
    description: "Jusqu'à 100 messages",
    bodyExample: { chatId: "229XXXXXXXX@c.us", count: 50 },
  },
  {
    method: "getMessage",
    label: "Détail d'un message",
    category: "journals",
    http: "POST",
    description: "Récupérer un message par id",
    bodyExample: { chatId: "229XXXXXXXX@c.us", idMessage: "ABC123" },
  },
  {
    method: "showMessagesQueue",
    label: "Voir file d'envoi",
    category: "queues",
    http: "GET",
    description: "Messages en attente d'envoi",
  },
  {
    method: "clearMessagesQueue",
    label: "Vider file d'envoi",
    category: "queues",
    http: "GET",
    description: "Supprime la file d'attente",
  },
  {
    method: "getGroupData",
    label: "Infos groupe",
    category: "groups",
    http: "POST",
    description: "Membres, sujet, taille",
    bodyExample: { groupId: "229XXXXXXXX-1234567890@g.us" },
  },
  {
    method: "createGroup",
    label: "Créer un groupe",
    category: "groups",
    http: "POST",
    description: "Nouveau groupe WhatsApp",
    bodyExample: { groupName: "Mon groupe", chatIds: ["229XXXXXXXX@c.us"] },
  },
  {
    method: "updateGroup",
    label: "Modifier groupe",
    category: "groups",
    http: "POST",
    description: "Changer nom ou photo",
    bodyExample: { groupId: "229XXXXXXXX-123@g.us", groupName: "Nouveau nom" },
  },
  {
    method: "addGroupParticipant",
    label: "Ajouter au groupe",
    category: "groups",
    http: "POST",
    bodyExample: { groupId: "229XXXXXXXX-123@g.us", participantChatId: "229YYYYYYYY@c.us" },
    description: "Ajouter un participant",
  },
  {
    method: "removeGroupParticipant",
    label: "Retirer du groupe",
    category: "groups",
    http: "POST",
    bodyExample: { groupId: "229XXXXXXXX-123@g.us", participantChatId: "229YYYYYYYY@c.us" },
    description: "Retirer un participant",
  },
  {
    method: "setGroupAdmin",
    label: "Définir admin",
    category: "groups",
    http: "POST",
    bodyExample: { groupId: "229XXXXXXXX-123@g.us", participantChatId: "229YYYYYYYY@c.us" },
    description: "Promouvoir administrateur",
  },
  {
    method: "leaveGroup",
    label: "Quitter le groupe",
    category: "groups",
    http: "POST",
    bodyExample: { groupId: "229XXXXXXXX-123@g.us" },
    description: "Quitter un groupe",
  },
  {
    method: "sendTextStatus",
    label: "Publier statut texte",
    category: "statuses",
    http: "POST",
    description: "Statut WhatsApp (bêta — accès requis)",
    bodyExample: {
      message: "Mon statut du jour",
      backgroundColor: "#228B22",
      font: "SERIF",
      participants: [],
    },
  },
  {
    method: "sendMediaStatus",
    label: "Publier statut média",
    category: "statuses",
    http: "POST",
    description: "Image/vidéo en statut",
    bodyExample: { urlFile: "https://example.com/photo.jpg", participants: [] },
  },
  {
    method: "sendVoiceStatus",
    label: "Publier statut vocal",
    category: "statuses",
    http: "POST",
    description: "Note vocale en statut",
    bodyExample: { urlFile: "https://example.com/voice.ogg", participants: [] },
  },
  {
    method: "deleteStatus",
    label: "Supprimer un statut",
    category: "statuses",
    http: "POST",
    bodyExample: { idMessage: "ABC123" },
    description: "Supprimer un statut publié",
  },
  {
    method: "getIncomingStatuses",
    label: "Statuts reçus",
    category: "statuses",
    http: "GET",
    description: "Historique statuts entrants",
    queryParams: ["minutes"],
  },
  {
    method: "getOutgoingStatuses",
    label: "Statuts publiés",
    category: "statuses",
    http: "GET",
    description: "Historique statuts sortants",
    queryParams: ["minutes"],
  },
  {
    method: "readChat",
    label: "Marquer comme lu",
    category: "marks",
    http: "POST",
    description: "Marquer tout ou un message comme lu",
    bodyExample: { chatId: "229XXXXXXXX@c.us" },
  },
  {
    method: "getChats",
    label: "Liste des chats",
    category: "service",
    http: "GET",
    description: "Chats triés par activité",
    queryParams: ["count"],
  },
  {
    method: "getContacts",
    label: "Liste contacts / groupes",
    category: "service",
    http: "GET",
    description: "group=true pour les groupes",
    queryParams: ["group", "count"],
  },
  {
    method: "checkWhatsapp",
    label: "Vérifier numéro WhatsApp",
    category: "service",
    http: "POST",
    description: "Le numéro a-t-il WhatsApp ?",
    bodyExample: { phoneNumber: 22900000000 },
  },
  {
    method: "getContactInfo",
    label: "Infos contact",
    category: "service",
    http: "POST",
    description: "Avatar, nom, statut",
    bodyExample: { chatId: "229XXXXXXXX@c.us" },
  },
  {
    method: "downloadFile",
    label: "Télécharger fichier",
    category: "media",
    http: "POST",
    description: "Télécharger média d'un message entrant",
    bodyExample: { chatId: "229XXXXXXXX@c.us", idMessage: "ABC123" },
  },
];

export function findGreenApiMethod(method: string): GreenApiMethodDef | undefined {
  return GREEN_API_METHODS.find((m) => m.method === method);
}

export const ALLOWED_GREEN_API_METHODS = new Set(GREEN_API_METHODS.map((m) => m.method));
